server:
  port: ${AUTH_PORT:8081}

spring:
  application:
    name: auth-service
  main:
    lazy-initialization: true
  # Database configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://db.dscvrpluimupwogilmqv.supabase.co:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Wedspot@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to validate later
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


# Register with eureka server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}






