server:
  port: 8761
  address: 127.0.0.1

spring:
  main:
    lazy-initialization: true
  application:
    name: service-registry


# Do not register itself
eureka:
  client:
    register-with-eureka: false
    fetch: false




