server:
  port: ${REGISTRY_PORT:8761}

spring:
  main:
    lazy-initialization: true
  application:
    name: service-registry


# Do not register itself
eureka:
  client:
    register-with-eureka: false
    fetch: false




